In [10]:
#testing data as scaled

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
from sklearn.metrics import max_error
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.naive_bayes import GaussianNB
import xgboost as xgb

In [36]:
data = pd.read_csv('data')
data = data.drop(columns=['taxi_out', 'taxi_in', 'air_time'])
data['arr_delay'] = data['arr_delay'].replace(np.NaN, 0)
data['dep_delay'] = data['dep_delay'].replace(np.NaN, 0)

In [45]:
#Below is funtion to define classifier and get predictions. 
#We can use "predict()" method that checks whether the trained algorithm perfirds well on test data 
def get_predictions(clf, X_train, y_train, X_test):
    # create classifier
    clf = clf
    # fit it to training data
    clf.fit(X_train,y_train)
    # predict using test data
    y_pred = clf.predict(X_test)
    # Compute predicted probabilities: y_pred_prob
    #y_pred_prob = clf.predict_proba(X_test)
    return y_pred

In [46]:
#Function to print the classifier's scores
def print_scores(y_test,y_pred):
    print('Mean Absolute Error: ', mean_absolute_error(y_test, y_pred))
    print('R2: ', r2_score(y_test, y_pred))
    print('Max Error: ', max_error(y_test, y_pred))

In [37]:
data = data.drop(columns = ['fl_date','origin_city_name', 'dest_city_name', 'dep_time', 'arr_time','dep_delay'])

In [41]:
y = data['arr_delay'].values.reshape(-1,1)
print(y)
X = data.drop(['arr_delay'],axis=1).values
print(X)

[[ 54.]
 [ -2.]
 [-10.]
 ...
 [-21.]
 [ -8.]
 [-15.]]
[[ 1.76000000e+02  7.26000000e+02  6.89167100e+00  1.16134454e+01
  -6.36363636e-01  2.95770393e+00]
 [ 1.18000000e+02  5.94000000e+02  4.83250600e+00  2.92668488e+00
   1.10000000e+00  2.98578298e+00]
 [ 1.83000000e+02  1.50600000e+03  3.89691100e+00  8.69790454e+00
  -1.30000000e+00  2.57928118e+00]
 ...
 [ 7.80000000e+01  3.68000000e+02  2.48986100e+00  2.07725322e+00
  -1.34583333e+01  4.80940951e+00]
 [ 9.80000000e+01  5.79000000e+02  2.48986100e+00  3.41290323e+01
  -1.20000000e+00  2.98578298e+00]
 [ 1.00000000e+02  5.00000000e+02  2.48986100e+00  1.09166667e+01
  -7.91666667e+00  2.98578298e+00]]


In [43]:
# scaling data to see if it makes a difference
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Normalizer

#scaling
scaler = StandardScaler()
scaler.fit(X)
X_scale = scaler.transform(X)
X_scale

array([[ 0.59825742, -0.07759678,  0.40627062,  1.26430886, -0.4347462 ,
        -0.53773112],
       [-0.21270355, -0.30228517, -0.27759524, -0.58309534, -0.31501769,
        -0.53216176],
       [ 0.69613202,  1.25010734, -0.58831414,  0.64426386, -0.48050631,
        -0.61278971],
       ...,
       [-0.77198697, -0.68697892, -1.05560718, -0.76374308, -1.31886705,
        -0.17045298],
       [-0.49234526, -0.32781794, -1.05560718,  6.05267502, -0.47361095,
        -0.53216176],
       [-0.46438109, -0.46229054, -1.05560718,  1.11612567, -0.93674924,
        -0.53216176]])

In [42]:
#scaling
scaler = StandardScaler()
scaler.fit(y)
y_scale = scaler.transform(y)
y_scale

array([[ 0.94156002],
       [-0.1493806 ],
       [-0.30522926],
       ...,
       [-0.51952117],
       [-0.26626709],
       [-0.40263467]])

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scale, y_scale, test_size=0.2,
                                                    random_state=42)


In [47]:
# Case-RandomForestRegressor-2 : added max_depth=3 == best result
y_pred = get_predictions(RandomForestRegressor(n_estimators=100, max_depth=3), X_train, y_train, X_test)
print_scores(y_test,y_pred)

C:\Users\Jaden\AppData\Local\Temp/ipykernel_7980/2621364092.py:11: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf.fit(X_train,y_train)


Mean Absolute Error:  0.47832286782734357
R2:  0.06932111562235244
Max Error:  21.798968953672993


In [49]:
from sklearn.neighbors import KNeighborsRegressor
# Case-KNeighborsClassifier-1: Does not perform as well
y_pred = get_predictions(KNeighborsRegressor(n_neighbors=1500), X_train, y_train, X_test)
print_scores(y_test,y_pred)

Mean Absolute Error:  0.4564185667245994
R2:  0.07325216647651345
Max Error:  21.832942644990638


In [50]:
from sklearn.linear_model import Ridge
# Case-Ridge-1: Best performer thus far, 0.122 R2!
y_pred = get_predictions(Ridge(alpha=1), X_train, y_train, X_test)
print_scores(y_test,y_pred)

Mean Absolute Error:  0.4555100611849898
R2:  0.12207192288302127
Max Error:  21.411385910661117


In [ ]:
#no big difference in the R2 values of the best performing models with scaling introduced